### ISSUE TITLE
Increase version of Polymer

### ISSUE THREAD

**Issue by rbenitez** [tzolov/viz-js#1]
Hi, I have seen that Polymer has a new version where the [compatibility with all bowsers](https://www.polymer-project.org/1.0/resources/compatibility.html) is better. 

Could you increase version of polymer to 1.0.0?

Thanks!

**Comment by rbenitez** [comment]
Hi again, 

I have been investigating and I have seen that for update  polymer to 1.0.0 version, the applications should have some changes,  using this guide (https://www.polymer-project.org/1.0/docs/migration.html) Could it do this changes? 

We use this library for kurento project.

Thanks a lot

**Comment by tzolov** [comment]
resolved
